#!/bin/bash
# GUIA DE TESTES MANUAIS para o islash (UEsh)
# Como o islash e' interactivo, este script apenas guia o utilizador
# atraves dos testes a executar dentro do shell.

echo "============================================="
echo "  TESTES: islash (interactivos)"
echo "============================================="
echo ""
echo "Este e' um guia para teste manual. O islash e' interactivo"
echo "e nao pode ser testado por script."
echo ""
echo "Preparacao:"
echo "  seq 1 20 > tests/exemplo.txt"
echo ""
echo "Lanca o shell com:"
echo "  ./bin/islash"
echo ""
echo "DENTRO do islash, escreve cada um destes comandos e Enter:"
echo ""
echo "  1.  pwd                              -> mostra o dir actual"
echo "  2.  echo Ola mundo                   -> 'Ola mundo'"
echo "  3.  echo                             -> linha vazia"
echo "  4.  sleep 2                          -> pausa 2 segundos"
echo "  5.  cd /tmp                          -> sem output"
echo "  6.  pwd                              -> '/tmp'"
echo "  7.  cd                               -> volta ao \$HOME"
echo "  8.  pwd                              -> dir do HOME"
echo "  9.  cd /naoexiste                    -> erro, mantem dir"
echo "  10. cd -                             -> (vai dar erro - nao suportamos)"
echo ""
echo "Voltar ao project root:"
echo "  cd ~/Desktop/Projecto_SO"
echo ""
echo "Testar comandos externos:"
echo "  11. ls                               -> ls do sistema (via PATH)"
echo "  12. ./bin/ls                         -> o teu ls"
echo "  13. ./bin/head -5 tests/exemplo.txt  -> primeiras 5 linhas"
echo "  14. ./bin/tail -3 tests/exemplo.txt  -> ultimas 3"
echo "  15. ./bin/grep -i 'hello' /etc/hosts -> qualquer grep"
echo "  16. date                             -> data e hora"
echo "  17. whoami                           -> teu username"
echo "  18. comandoinexistente               -> erro 'No such file'"
echo ""
echo "Sair:"
echo "  19. exit                             -> volta ao bash"
echo "  (ou Ctrl+D - tambem termina por EOF)"
echo ""
echo "============================================="
echo "  Caso especial: Ctrl+C"
echo "============================================="
echo "Dentro do islash, faz:"
echo "  sleep 100"
echo "Depois preme Ctrl+C - o sleep deve ser interrompido"
echo "mas o shell deve sobreviver e mostrar novo prompt."
echo ""
echo "Se quiseres mesmo correr (mostra-te os comandos a fazer):"
read -p "Lancar o islash agora? (s/n): " resposta
if [ "$resposta" = "s" ] || [ "$resposta" = "S" ]; then
    ./bin/islash
fi
